✨ NEW: Add required field numbered to containers, math, headings
executablebooks/myst-spec pull request #36
Opened 2022-04-08 20:55 UTC by fwkoch

This PR is to address numbering of different node types upon render, when authors want sequential figure / table / equation / header numbers (as can be done in latex / pandoc / sphinx). While numbers themselves will be added after the fact as a transform on the AST, we do need to specify if nodes should be `numbered`.

Previously, we had a small start at this: `containers` had an optional `numbered` property. This PR adds that property to `headings` and `math` and also makes it required (with an implied default of `true`).

2022-04-08 21:04 UTC, rowanc1 approved these changes
Looks good to me!

This is something that is critical in scientific writing, and the ability to skip numbering for a section header of figure (using `{-}` in pandoc, or `\section*{}` in latex).

2022-04-08 21:04 UTC, rowanc1 commented on schema/math.schema.json
> +            },
Nice!

2022-04-08 21:04 UTC, rowanc1 commented on schema/commonmark.schema.json
> +            },
Looks good!

2022-04-09 07:56 UTC, chrisjsewell commented
> makes it required (with an implied default of true).

Why does this need to be required? I don't think this should be the case.
Definitely +1 for having it in the schema 👍, but I think processors of the AST can decide what the implied default is, probably via configuration available to the user

2022-04-09 07:57 UTC, chrisjsewell requested changes
see coment

2022-04-09 08:03 UTC, chrisjsewell commented
In general, I would say that most fields that are boolean, should also be allowed to be `undefined`.
This is true of other things in mdast, such as `List.ordered` and `List.spread`

2022-04-11 17:08 UTC, rowanc1 commented on schema/commonmark.schema.json
> +            "number": {
enumerator

2022-04-11 17:11 UTC, rowanc1 commented on docs/examples/commonmark.headings.yml
> +          numbered: true
Remove these!

2022-04-11 18:05 UTC, merged